courses:
  - title: course1
    organization: easymind 2020 11 24 gdpr course group
    coursewares:
      - title: "Data Protection and Destruction"
        href: "D:\\temps\\test\\dpd"
      - title: "GDPR in Action"
        href: "D:\\temps\\test\\gdpr2"
      - title: "GDPR Overview"
        href: "D:\\temps\\test\\gdpr"
      - title: "Insider Threat Overview"
        href: "D:\\temps\\test\\ito"
      - title: "Malicious Insider Threat"
        href: "D:\\temps\\test\\itm"
      - title: "Unintentional Insider Threat"
        href: "D:\\temps\\test\\itu"
      - title: "Mobile App Permissions"
        href: "D:\\temps\\test\\map"
      - title: "Mobile App Security"
        href: "D:\\temps\\test\\mba1"
      - title: "Mobile Device Security"
        href: "D:\\temps\\test\\mbd"
      - title: "Beyond Passwords"
        href: "D:\\temps\\test\\ppp"
      - title: "Multi-Factor Authentication"
        href: "D:\\temps\\test\\mfa"
      - title: "Password Management"
        href: "D:\\temps\\test\\pwm"
      - title: "Password Policy"
        href: "D:\\temps\\test\\pwd"
      - title: "PCI DSS"
        href: "D:\\temps\\test\\pci"
      - title: "PII Fundamentals"
        href: "D:\\temps\\test\\pii1"
      - title: "PII in Action"
        href: "D:\\temps\\test\\pii2"
      - title: "Physical Security"
        href: "D:\\temps\\test\\phy1"
      - title: "Identifying Compromised Accounts"
        href: "D:\\temps\\test\\compa"
      - title: "Mitigating Compromised Devices"
        href: "D:\\temps\\test\\compd"
      - title: "Protected Health Information"
        href: "D:\\temps\\test\\phi"
      - title: "Email Protection Tools"
        href: "D:\\temps\\test\\eml2"
      - title: "Email Security on Mobile Devices"
        href: "D:\\temps\\test\\eml6"
      - title: "Spear Phishing Threats"
        href: "D:\\temps\\test\\eml7"
      - title: "Avoiding Dangerous Attachments"
        href: "D:\\temps\\test\\eml4"
      - title: "Avoiding Dangerous Links"
        href: "D:\\temps\\test\\eml3"
      - title: "Data Entry Phishing"
        href: "D:\\temps\\test\\eml5"
      - title: "Introduction to Phishing"
        href: "D:\\temps\\test\\eml1"
      - title: "Video: Data Entry Phishing"
        href: "D:\\temps\\test\\veml5"
      - title: "Video: Introduction to Phishing"
        href: "D:\\temps\\test\\veml1"
      - title: "Security Beyond the Office"
        href: "D:\\temps\\test\\sbo"
      - title: "Security Essentials"
        href: "D:\\temps\\test\\ess"
      - title: "Security Essentials for Executives"
        href: "D:\\temps\\test\\exc"
      - title: "Social Engineering"
        href: "D:\\temps\\test\\eng"
      - title: "Travel Security"
        href: "D:\\temps\\test\\tra"
      - title: "USB Device Safety"
        href: "D:\\temps\\test\\usb"
      - title: "Video: Mobile Device Security"
        href: "D:\\temps\\test\\vmbd"
      - title: "Video: Security Essentials"
        href: "D:\\temps\\test\\vess"