courses:
  - title: URL培训
    organization: easymind 2020 11 24 gdpr course group
    coursewares:
      - title: "学习如何找出欺诈性URL"
        href: "D:\\temps\\test1\\v2-production-1568654256"
        parameters: "module=url"